export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_MENTOR_SUCCESS = 'FETCH_MENTOR_SUCCESS';
export const FETCH_MENTOR_FAILED = 'FETCH_MENTOR_FAILED ';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_FINISH = 'REQUEST_FINISH';
