export const ASCENDING_POPULARITY = 'ASCENDING_POPULARITY';
export const DESCENDINGLY_POPULARITY = 'DESCENDINGLY_POPULARITY';
export const ASCENDING_DATE = 'ASCENDING_DATE';
export const DESCENDINGLY_DATE = 'DESCENDINGLY_DATE';

export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const RECEIVE_MOVIE_FAILED = 'RECEIVE_MOVIE_FAILED';
export const REQUEST_MOVIE = 'REQUEST_MOVIE';

export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_MOVIES_FAILED = 'RECEIVE_MOVIES_FAILED';
export const REQUEST_MOVIES = 'REQUEST_MOVIES';
